name: ci-build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image Tag"
        required: true

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-18.04

    steps:
      - name: Check out the ${{ github.event.inputs.tag }} tag to build
        uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ github.event.inputs.tag }}

      - name: Check out the ${{ github.ref }} branch for Dockerfile
        uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}
          path: main_branch

      - name: Copy Dockerfile from ${{github.ref}} to ${{ github.event.inputs.tag }}
        run: |
          cp ${{ github. workspace }}/main_branch/Dockerfile Dockerfile
          rm -rf ${{ github. workspace }}/main_branch

      - name: Build Docker image ${{ github.event.inputs.tag }} and Push to DockerHub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_REPO }}
          tags: ${{ github.event.inputs.tag }}
