name: ci-build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image Tag"
        required: true

jobs:
  push_to_registry:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-18.04

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
        id: extract_branch

      - name: Check out the ${{ github.event.inputs.tag }} tag to build
        uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ github.event.inputs.tag }}

      - name: Check out the ${{ steps.extract_branch.outputs.branch }} branch for Dockerfile
        uses: actions/checkout@v2
        with:
          ref: ${{github.ref}}
          path: main_branch

      - name: Copy Dockerfile from ${{ steps.extract_branch.outputs.branch }} branch to ${{ github.event.inputs.tag }}
        run: |
          cp ${{ github. workspace }}/main_branch/Dockerfile Dockerfile
          rm -rf ${{ github. workspace }}/main_branch

      # GitHub Action to build and push Docker images with Buildx https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image ${{ secrets.DOCKER_REPO }}:${{ github.event.inputs.tag }}
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_REPO }}:${{ github.event.inputs.tag }}
